### ISSUE TITLE
About anno json

### ISSUE THREAD

**Issue by MoonBunnyZZZ** [noirmist/Pytorch_Pose_Proposal_Network#1]
@noirmist How to produce the json file , anno json file and new anno json file ,that used for train and val?
The data directory just contain part code.And the mpii dataset only offer annotation mat file .

**Comment by noirmist** [comment]
Sorry for missing file.
You can use [this code](https://github.com/noirmist/Pytorch_Pose_Proposal_Network/blob/master/data/convert_mpii_dataset.py) to convert mat file to json file
