### ISSUE TITLE
what is the joint named 'stomach'?

### ISSUE THREAD

**Issue by oujieww** [noirmist/Pytorch_Pose_Proposal_Network#3]
thanks for your nice sharing! i only use mpii data, and use your convert code, but i do not know what is stomach?

**Comment by noirmist** [comment]
Your welcome!.
It's middle point of neck and pelvis.

**Comment by oujieww** [comment]
thanks for your reply, and , which code should i use for this joint?

**Comment by noirmist** [comment]
I guess, I miss upload file. I will look in to it in couple weeks.

**Comment by noirmist** [comment]
Sorry for late reply.
The stomach joint is added during data refining step.

[Here](https://github.com/noirmist/Pytorch_Pose_Proposal_Network/blob/a0561f921e3a49444d5966ae104cbbf9886f6050/data/data_refine.py#L245) is the detail code.
